#RGBåŸŸ
exposure:
  min:-3.50
  max:3.50
  default:1.0

white_balance:
  r_gain:
    min:0.6
    max:1.65
    default:1.0
  g_gain:
    min:0.6
    max:1.65
    default:1.0
  b_gain:
    min:0.6
    max:1.65
    default:1.0

ccm:
  default: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]

saturation:
  min:0.5
  max:1.5
  default:1.0

desaturation:
  min: 0.0
  max: 0.5
  default: 0.0

contrast:
  min: 0.8
  max: 1.5
  default: 1.0

sharpen:
  alpha_min: 0.0
  alpha_max: 2.0
  default: 0.8
  kernel_size: 3

denoise:
  h_color_min: 3.0
  h_color_max: 20.0
  h_color_default: 8.0
  templateWindowSize: 7
  searchWindowSize: 21

tone_mapping:
  method: "reinhard"  # reinhard/simple/hard
  exposure_bias:
    min: -1.0
    max: 1.0
    default: 0.0

gamma:
  min: 0.8
  max: 2.2
  default: 1.0